[profile.release]
lto = true

[workspace]
members = [
  "lib/",
  "shio-macro",
  "examples/hello",
  "examples/json",
  "examples/proxy",
  "examples/stateful",
  "examples/redirect",
  "examples/templates_askama",
  "examples/postgres",
  "examples/managed_state",
  "examples/hello_macro",
]
